name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - 2.x
      - 3.x
      - symfony-5.4

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.4"
        symfony-versions:
          - "^5.4"
    name: PHP ${{ matrix.php }} Symfony ${{ matrix.symfony-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ matrix.php }}-${{ matrix.symfony-versions }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-
            composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-versions }}
        run: composer update

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit
